# permissions for end users to edit mycontrollers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mycontroller-editor-role
rules:
- apiGroups:
  - mycontroller.org
  resources:
  - mycontrollers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mycontroller.org
  resources:
  - mycontrollers/status
  verbs:
  - get
