apiVersion: mycontroller.org/v1
kind: MyController
metadata:
  name: myc-storage
spec:
  secret: my-secret
  disable_analytics: true
  log_level: info
  storage:
    storage_class_name: ""
    data_size: "5Gi"
    metric_size: "5Gi"
