name: publish container images
on:
  push:
    branches: [master]

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
      - name: checkout source code
        uses: actions/checkout@v2

      - name: Login in to quay.io registry
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - uses: actions/setup-go@v2
        with:
          go-version: ^1.16
      
      - uses: jpkrohling/setup-operator-sdk@v1.1.0
        with:
          operator-sdk-version: v1.11.0

      - name: Build container and push
        run: |
          make generate
          make docker-build docker-push # operator image
          make bundle bundle-build bundle-push # operator bundle image
