name: publish container images
on:
  push:
    branches: [master]

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
      - name: checkout source code
        uses: actions/checkout@v2

       - name: Login in to quay.io registry
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build container and push - ${{ matrix.container_image }}
        run: |
          make generate
          make docker-build docker-push # operator image
          make bundle bundle-build bundle-push # operator bundle image
